[package]
name = "simple-rust-discord"
version = "0.1.1"
edition = "2021"

[dependencies]
serenity = { version = "0.12", default-features = false, features = ["client", "gateway", "model", "rustls_backend"] }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread"] }
